MyProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weber.urls')),
    path('blog/', include('blog.urls')),
    path('products/', include('products.urls')),
    path('order/', include('order.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('cart/', include('order.urls')),


    # path('order/', include('order.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

urlpatterns = [
    path('', views.blog, name = 'blog'),
    path('post/<post_id>/', views.post_id, name = 'post_id'),
    path('tags/<tag_id>', views.tag_id, name = 'tag_id')

]

weber/urls.py
from django.contrib import admin
from django.urls import path
from weber import views

urlpatterns = [
    path('', views.weber, name = 'weber')
]

weber/models.py
from django.db import models

class Profile(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=100)

    def __str__(self):
        return "Имя: %s, Id: %s" % (self.name, self.id)

weber/forms.py
from django import forms
from .models import *

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        exclude = []

weber/views.py
from .forms import ProfileForm
from django.shortcuts import render
from products.models import Product
from products.models import ProductImage
from blog.models import *

# Create your views here.
def weber(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_best_sellers = products_images.filter(product__is_best_seller=True)
    products_images_new = products_images.filter(product__is_new=True)
    products_images_seller = products_images.filter(product__is_sale=True)
    products_images_top_rate = products_images.filter(product__is_top_rate=True)
    post_images = PostImage.objects.filter(is_active=True, post__is_active=True).order_by("-created")[:3]

    return render(request, 'index/index.html', locals())

templates/weber/weber.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{%  static "css/grid.css" %}">

    <title>Добро пожаловать в AppleStore</title>
</head>
<body>
<style>

</style>
<div class="weber-main">
    <div class="weber-shadow-main">
<div class="container">
<div class="subscripe col-md-7 col-md-offset-2">
    <h1 class="title">Здравствуйте, наш магазин скоро откроется!</h1>
    <p>Сообщить о открытии</p>
    <style>.bar:before,label{transition:.3s ease all}.btn,form h5{text-transform:uppercase}.btn,input:focus,textarea:focus{outline:0}.btn-box,form h1,form h5{text-align:center}form{width:320px;margin:45px auto}form h1{font-size:3em;font-weight:300;color:#2196f3}form h5{color:#c6c6c6}form hr.sep{background:#2196f3;box-shadow:none;border:none;height:2px;width:25%;margin:0 auto 45px}.bar,input:focus~.bar:before,textarea:focus~.bar:before{width:320px}form .emoji{font-size:1.2em}.group{position:relative;margin:45px 0}textarea{resize:none}input,textarea{background:0 0;color:#c6c6c6;font-size:18px;padding:10px 10px 10px 5px;display:block;width:320px;border:none;border-radius:0;border-bottom:1px solid #c6c6c6}input:focus~label,input:valid~label,textarea:focus~label,textarea:valid~label{top:-14px;font-size:12px;color:#2196f3}input[type=password]{letter-spacing:.3em}label{color:#c6c6c6;font-size:16px;font-weight:400;position:absolute;pointer-events:none;left:5px;top:10px}.bar{position:relative;display:block}.bar:before{content:"";height:2px;width:0;bottom:0;position:absolute;background:#2196f3;left:0}.btn{background:#fff;color:#959595;border:none;padding:10px 20px;border-radius:3px;letter-spacing:.06em;text-decoration:none;box-shadow:0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24);transition:all .3s cubic-bezier(.25,.8,.25,1)}.btn:hover{color:#8b8b8b;box-shadow:0 7px 14px rgba(0,0,0,.18),0 5px 5px rgba(0,0,0,.12)}.btn.btn-link{background:#2196f3;color:#d3eafd}.btn.btn-link:hover{background:#0d8aee;color:#deeffd}.btn.btn-submit{background:#2196f3;color:#bce0fb}.btn.btn-submit:hover{background:#0d8aee;color:#deeffd}.btn.btn-cancel{background:#eee}.btn.btn-cancel:hover{background:#e1e1e1;color:#8b8b8b}.btn-box{margin:50px 0}</style>
        <form method="POST" class="form-sub" action="">
            <input type="hidden" name="csrfmiddlewaretoken" value="4FtLp0ZWp9pb43SLNmM68mk2eGTB7Dt5Te9qNzoovzlNpaVwMaSFP0LQtF4thpWO">
            <div class="group">
      <input type="email" autocomplete="off" name="email" maxlength="254" required="" id="id_email"/><span class="highlight"></span><span class="bar"></span>
      <label>Email</label>
    </div>
    <div class="group">
      <input type="text" autocomplete="off" name="name" maxlength="100" required="" id="id_name"/><span class="highlight"></span><span class="bar"></span>
      <label>Name</label>
    </div>
            <input class="btn btn-submit" value="Подписаться" type="submit">
        </form>

    </div>
    </div>
</div>
    </div>
</div>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{%  static "css/main.css" %}">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Sans+Pro:200,300,400,600" rel="stylesheet">
</body>
</html>