MyProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weber.urls')),
    path('blog/', include('blog.urls')),
    path('products/', include('products.urls')),
    path('order/', include('order.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('cart/', include('order.urls')),


    # path('order/', include('order.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

urlpatterns = [
    path('', views.blog, name = 'blog'),
    path('post/<post_id>/', views.post_id, name = 'post_id'),
    path('tags/<tag_id>', views.tag_id, name = 'tag_id')

]

products/urls.py
from django.contrib import admin
from django.urls import path
from products import views

urlpatterns = [
    path('', views.products, name = 'products'),
    path('product/<product_id>/', views.product, name = 'product'),
    path('category/<product_category>/', views.product_category, name = 'product_category'),
    path('search/', views.product_search, name = 'product_search'),
    path('accessories/<product_id>/', views.accessories_products, name = 'accessories'),
    path('clothing/<product_id>/', views.clothing_products, name = 'clothing'),
    path('accesories/', views.accessories, name = 'accessories'),
    path('price/', views.price_sort, name = 'price_sort'),
    path('sale/', views.sale, name = 'sale'),
    path('<sex>/', views.sex, name = 'sex'),

    # path('accesories/', views.accessories, name = 'accessories'),
    # path('sale/', views.sale, name = 'sale'),
    # url(r'^u/(?P<id>\w+)/$', views.products, name = 'product')
]

products/models.py
from django.db import models
# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'

# ======================================================================================================

class ProductSex(models.Model):
    name_sex = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name_sex

    class Meta:
        verbose_name = 'Пол'
        verbose_name_plural = 'Полы'

# ======================================================================================================

class ProductClass(models.Model):
    name_class = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name_class

    class Meta:
        verbose_name = 'Class'
        verbose_name_plural = 'Classes'


# class ProductColors(models.Model):
#     name_color = models.CharField(max_length=64, blank=True, null=True)
#     is_active = models.BooleanField(default=True)
#
#     def __str__(self):
#         return "%s" % self.name_color
#
#     class Meta:
#         verbose_name = 'Цвет'
#         verbose_name_plural = 'Цвета'


class Product(models.Model):
    product_name = models.CharField(max_length=100, blank=True, null=False, default=None)
    product_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, null=False)
    product_description = models.TextField(blank=True, null=True, default=None)
    product_category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, default=1, null=False)
    product_class = models.ForeignKey(ProductClass, on_delete=models.CASCADE, default=1, null=False)
    sex = models.ForeignKey(ProductSex, on_delete=models.CASCADE, default=1, null=False)
    product_number = models.CharField(max_length=10, blank=True, default='JH-172', null=False)
    paramount = '1'
    secondary = '2'
    YEAR_IN_SCHOOL_CHOICES = (
        (secondary, 'Secondary'),
        (paramount, 'Paramount')
    )
    importance = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=1
    )
    is_best_seller = models.BooleanField(default=False)
    is_top_rate = models.BooleanField(default=False)
    is_new = models.BooleanField(default=False)
    is_sale = models.BooleanField(default=False)
    sale = models.IntegerField(blank=True, null=True, default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

# ======================================================================================================

# class ProductColor(models.Model):
#     name_color = models.ForeignKey(ProductColors, on_delete=models.CASCADE, null=True)
#     is_main =  models.BooleanField(default=False)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     is_active = models.BooleanField(default=True)
#
#
#     def __str__(self):
#         return self.product.product_name
#
#     class Meta:
#         verbose_name = 'Цвет'
#         verbose_name_plural = 'Цвета'



class ProductImage(models.Model):
    is_main =  models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/media/productsImg/')
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фотографии'

products/views.py
from django.shortcuts import render
from products.models import Product
from products.models import ProductImage
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage



def products(request):
    sort = request.GET.get('sort')
    if sort == None or sort == 'def' or sort == "None":
        products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True).order_by('-product__importance')

        paginator = Paginator(products_images, 12)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        vars = dict(
            posts=posts,
        )

        return render(request, 'product/shop.html', locals())

    elif sort == 'lowth':
        products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True).order_by(
            'product__product_price')

        paginator = Paginator(products_images, 12)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        vars = dict(
            posts=posts,
        )

        return render(request, 'product/shop.html', locals())


    elif sort == 'htlow':
        products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True).order_by(
            '-product__product_price')

        paginator = Paginator(products_images, 12)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        vars = dict(
            posts=posts,
        )

        return render(request, 'product/shop.html', locals())




    # ======================================================================================================

def product(request, product_id):
    product = Product.objects.get(id=product_id)
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product_id=product_id)
    products_related = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)

    return render(request, 'products/product.html', locals())


    # ======================================================================================================

def sex(request, sex):
    sort = request.GET.get('sort')
    if sort == None or sort == 'def' or sort == "None":
        products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__sex=sex).order_by(
            '-product__importance')

        paginator = Paginator(products_images, 12)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        vars = dict(
            posts=posts,
        )

        return render(request, 'product/shop.html', locals())

    elif sort == 'lowth':
        products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__sex=sex).order_by(
            'product__product_price')

        paginator = Paginator(products_images, 12)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        vars = dict(
            posts=posts,
        )

        return render(request, 'product/shop.html', locals())


    elif sort == 'htlow':
        products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__sex=sex).order_by(
            '-product__product_price')

        paginator = Paginator(products_images, 12)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        vars = dict(
            posts=posts,
        )

        return render(request, 'product/shop.html', locals())

    # ======================================================================================================

def accessories(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__product_class=4).order_by('-product__importance')
    paginator = Paginator(products_images, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    vars = dict(
        posts=posts,
    )

    return render(request, 'products/product_accessories.html', locals())

    # ======================================================================================================

def sale(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__is_sale=True).order_by('-product__importance')
    paginator = Paginator(products_images, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    vars = dict(
        posts=posts,
    )

    return render(request, 'product/shop.html', locals())


    # ======================================================================================================

def accessories_products(request, product_id):
    product = Product.objects.get(id=product_id)
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__product_class=4).order_by('-product__importance')
    paginator = Paginator(products_images, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    vars = dict(
        posts=posts,
    )

    return render(request, 'products/product_accessories.html', locals())

    # ======================================================================================================

def clothing_products(request, product_id):
    product = Product.objects.get(id=product_id)
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__product_class=2)
    paginator = Paginator(products_images, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    vars = dict(
        posts=posts,
    )

    return render(request, 'product/product_clothing.html', locals())

    # ======================================================================================================

def product_category(request, product_category):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__product_category_id=product_category)
    paginator = Paginator(products_images, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    vars = dict(
        posts=posts,
    )

    return render(request, 'product/shop.html', locals())

    # ======================================================================================================

def product_search(request,  *args, **kwargs):
    question = request.GET.get('q')
    if len(question) < 100:
        products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__product_name__contains = question).order_by('-product__importance')
        if len(products_images) > 0:
            paginator = Paginator(products_images, 12)
            page = request.GET.get('page')
            try:
                posts = paginator.page(page)
            except PageNotAnInteger:
                posts = paginator.page(1)
            except EmptyPage:
                posts = paginator.page(paginator.num_pages)
            vars = dict(
                posts=posts,
            )
        else:
            not_find = True
    else:
        max_lenght = True


    return render(request, 'product/shop.html', locals())

    # ======================================================================================================

def add_to_cart(request, product_id):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__id=product_id)

    return True

    # ======================================================================================================

def price_sort(request, *args, **kwargs):
    price_min = request.GET.get('min')
    price_max = request.GET.get('max')
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True, product__product_price__gte = price_min,
                                                  product__product_price__lte = price_max)
    paginator = Paginator(products_images, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)

templates/products/product.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
	<title>Product detail</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'new/images/icons/favicon.png' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/fonts/themify/themify-icons.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/fonts/elegant-font/html-css/style.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/vendor/slick/slick.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'new/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'new/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body class="animsition">
{% include 'base/header.html' %}
<style>.m-text8{font-size: 22px;}.m-text7{font-size: 22px;}</style>
<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
		<a href="/" class="s-text16">
			Home
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<a href="/products/" class="s-text16">
			Shop
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>
		<span class="s-text17">
			{{ product.product_name }}
		</span>
	</div>
{% for products_image in products_images %}
    <input id = "product_img_main" type="hidden" img = "/{{ products_image.image.url }}">
{% endfor %}

	<!-- Product Detail -->
	<div class="container bgwhite p-t-35 p-b-80">
		<div class="flex-w flex-sb">
			<div class="w-size13 p-t-30 respon5">
				<div class="wrap-slick3 flex-sb flex-w">
					<div class="wrap-slick3-dots"></div>

					<div class="slick3">

                        {% for image_item in product.productimage_set.all %}
						<div class="item-slick3" data-thumb="/{{ image_item.image.url }}">
							<div class="wrap-pic-w">
								<img src="/{{ image_item.image.url }}" alt="IMG-PRODUCT">
							</div>
						</div>
                        {% endfor %}
					</div>
				</div>
			</div>

			<div class="w-size14 p-t-30 respon5">
				<h4 class="product-detail-name m-text16 p-b-13">
					{{ product.product_name }}
				</h4>

				<span class="m-text17">
					{% if product.is_sale == True %}
                            <span class="block2-oldprice m-text7 p-r-5">
                                ${{ product.product_price }}
							</span>
                            <span class="block2-newprice m-text8 p-r-5">
                                <script>
                                    var oldPrice = '{{ product.product_price }}';
                                    var sale = '{{ product.sale }}';
                                    var newPrice;
                                    if (sale > 0 ){
                                        newPrice = oldPrice - ((sale/100)*oldPrice);
                                        document.write('$' + newPrice.toFixed(2));
                                    }
                                    else {
                                        document.write('$' + '{{ product.product_price }}');
                                    }
                                </script>
						    </span>
                         {% endif %}
                    {% if product.is_sale == False %}
                            <span style="font-size: 22px;" class="block2-price m-text6 p-r-5">
							${{ product.product_price }}
						</span>
                         {% endif %}
				</span>

				<p class="s-text8 p-t-10">
					{{ product.product_description }}
				</p>
                <div class="p-t-33 p-b-60">
                {% if product.product_class.id == 3 %}
                    <!--  -->

					<div class="flex-m flex-w p-b-10">
						<div class="s-text15 w-size15 t-center">
							Size
						</div>

						<div class="rs2-select2 rs3-select2 bo4 of-hidden w-size16">
							<select class="selection-2" name="size">
								<option>Choose an option</option>
								<option>Size S</option>
								<option>Size M</option>
								<option>Size L</option>
								<option>Size XL</option>
							</select>
						</div>
					</div>
                {% endif %}




					<div class="flex-r-m flex-w p-t-10">
						<div class="w-size16 flex-m flex-w">
							<div class="flex-w bo5 of-hidden m-r-22 m-t-10 m-b-10">
								<button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-minus" aria-hidden="true"></i>
								</button>

								<input class="size8 m-text18 t-center num-product" type="number" name="num-product" value="1">

								<button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-plus" aria-hidden="true"></i>
								</button>
							</div>

							<div class="btn-addcart-product-detail size9 trans-0-4 m-t-10 m-b-10">
								<!-- Button -->
								<button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4 add_card_product" id="{{ product.id }}">
                                    {% csrf_token %}
									Add to Cart
								</button>
							</div>
						</div>
					</div>
				</div>
                <style>.m-text8{font-size: 16px;}.m-text7{font-size: 16px;}</style>
				<div class="p-b-45">
					<span class="s-text8 m-r-35">SKU: {{ product.product_number }}</span>
					<span class="s-text8">Categories: Mug, Design</span>
				</div>

				<!--  -->
				<div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
					<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
						Description
						<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
						<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
					</h5>

					<div class="dropdown-content dis-none p-t-15 p-b-23">
						<p class="s-text8">
							Fusce ornare mi vel risus porttitor dignissim. Nunc eget risus at ipsum blandit ornare vel sed velit. Proin gravida arcu nisl, a dignissim mauris placerat
						</p>
					</div>
				</div>

				<div class="wrap-dropdown-content bo7 p-t-15 p-b-14">
					<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
						Additional information
						<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
						<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
					</h5>

					<div class="dropdown-content dis-none p-t-15 p-b-23">
						<p class="s-text8">
							Fusce ornare mi vel risus porttitor dignissim. Nunc eget risus at ipsum blandit ornare vel sed velit. Proin gravida arcu nisl, a dignissim mauris placerat
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- Relate Product -->
	<section class="relateproduct bgwhite p-t-45 p-b-138">
		<div class="container">
			<div class="sec-title p-b-60">
				<h3 class="m-text5 t-center">
					Related Products
				</h3>
			</div>

			<!-- Slide2 -->
            <div class="wrap-slick2">
				<div class="slick2">
					{% for productimage in products_related  %}
                        {% if productimage.product.id != product.id and productimage.product.sex == product.sex %}
				            {% include 'base/product_block.html' %}
                        {% endif %}
                    {% endfor %}
				</div>
			</div>

        </div>
    </section>


{% include 'base/footer.html' %}

	<!-- Container Selection -->
	<div id="dropDownSelect1"></div>
	<div id="dropDownSelect2"></div>



<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'new/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'new/vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'new/vendor/bootstrap/js/popper.js'%}"></script>
	<script type="text/javascript" src="{% static 'new/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'new/vendor/select2/select2.min.js'%}"></script>
	<script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});

		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect2')
		});
	</script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'new/vendor/slick/slick.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'new/js/slick-custom.js'%}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'new/vendor/sweetalert/sweetalert.min.js'%}"></script>
	<script type="text/javascript">
		{#$('.block2-btn-addcart').each(function(){#}
		{#	var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();#}
		{#	$(this).on('click', function(){#}
		{#		swal(nameProduct, "is added to cart !", "success");#}
		{#	});#}
		{#});#}

		{#$('.block2-btn-addwishlist').each(function(){#}
		{#	var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();#}
		{#	$(this).on('click', function(){#}
		{#		swal(nameProduct, "is added to wishlist !", "success");#}
		{#	});#}
		{#});#}
        {##}
		{#$('.btn-addcart-product-detail').each(function(){#}
		{#	var nameProduct = $('.product-detail-name').html();#}
		{#	$(this).on('click', function(){#}
		{#		swal(nameProduct, "is added to wishlist !", "success");#}
		{#	});#}
		{#});#}
	</script>

<!--===============================================================================================-->
	<script src="{% static 'new/js/main.js' %}"></script>

</body>
</html>